# Generated by Django 3.2.7 on 2021-10-03 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_main', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_score', models.PositiveIntegerField()),
                ('team_2_score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaguestats.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('average_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('number_of_played_games', models.PositiveSmallIntegerField()),
                ('played_games', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leaguestats.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='playing_players',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaguestats.player'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('number_of_players', models.PositiveSmallIntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='leaguestats.coach')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaguestats.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leaguestats.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leaguestats.team'),
        ),
    ]
