# Generated by Django 3.2.7 on 2021-10-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaguestats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='average_score',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
