# Generated by Django 3.2.7 on 2021-10-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaguestats', '0002_auto_20211003_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leaguestats.team'),
        ),
    ]
