# Generated by Django 3.2.7 on 2021-10-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaguestats', '0004_alter_team_number_of_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
    ]
