# Generated by Django 3.2.7 on 2021-10-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaguestats', '0007_auto_20211003_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
