# Generated by Django 3.2.7 on 2021-10-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaguestats', '0008_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winning_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leaguestats.team'),
        ),
    ]
