# Generated by Django 3.2.7 on 2021-10-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaguestats', '0009_game_winning_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_2_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
